# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain Java versions, and provides a first line of defence against bad commits.

name: Java CI with Gradle

on:
  push:
    branches: [ 1.12.2 ]
  pull_request:
    branches: [ 1.12.2 ]

jobs:
  build:
    strategy:
      matrix:
        java: [
            "8",  # Minecraft default
            "11" # Current Java LTS
          ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: ${{ matrix.java }}

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
